name: build.Hutch.Relay.yml
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - app/Hutch.Relay/**
      - test/Hutch.Relay.Tests/**
      - .github/workflows/build.Hutch.Relay.yml
env:
  # Configure these
  CI_build-config: release
  CI_dotnet-version: 8.0.x
  CI_project: ./app/Hutch.Relay/Hutch.Relay.csproj
  Hutch_Relay_test_project: ./tests/Hutch.Relay.Tests/Hutch.Relay.Tests.csproj

  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.CI_dotnet-version }}
      - name: dotnet build
        run: >-
          dotnet build
          ${{ env.CI_project }}
          -c ${{ env.CI_build-config }}
      - name: Run Hutch.Relay Tests
        run: >-
          dotnet test
          ${{ env.Hutch_Relay_test_project }}
          -c ${{ env.CI_build-config }}
