# Publish RACKit nuget packages to the dev feed (Github Packages)

# This happens automatically for `main` to function as effective "nightlies"
# TODO: But should be doable manually for any ref

# NOTE: dev feed packages are pre-release versioned by UTC build timestamp, to ensure correct precedence.
# source ref and commit hash are recorded as metadata for informational / feed selection use, but this doesn't affect precedence (per semver).
# e.g. <Project Version>-<build timestamp as pre-release tag>+<source ref>.<commit hash> e.g. `0.1.0-20240821082421+main.96u7bd07`
# TODO: consider preserving existing VersionSuffix pre-release tags e.g. `0.1.0-beta.1` => `0.1.0-beta.1.20240821082421+main.96u7bd07`
# currently this workflow will replace `beta.1` with only the build timestamp

name: Publish Hutch.RACKit Dev Feed

on:
  workflow_dispatch:
  # TODO: testing
  pull_request:
    branches: [main]
    paths: [lib/Hutch.Rackit/**]
  push:
    branches: [main]
    paths: [lib/Hutch.Rackit/**]

env:
  # Configure these
  build-config: release
  dotnet-version: 8.0.x
  project: lib/Hutch.Rackit

  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.dotnet-version }}
      
      - uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 8
      
      - name: Set timestamp env var
        run: echo "RUN_TIMESTAMP=$(TZ="Etc/UTC" date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: dotnet pack
        run: >-
          dotnet pack
          ${{ env.project }}
          -c ${{ env.build-config }}
          -o ${{ github.workspace }}
          -p:VersionSuffix=${{ env.RUN_TIMESTAMP }}+${{ github.ref_name }}.${{ env.SHA }}
      
      - name: Add Github Packages Nuget Source
        run: >-
          dotnet nuget add source
          --username ${{ github.actor }}
          --password ${{ secrets.GITHUB_TOKEN }}
          --store-password-in-clear-text
          --name github
          "https://nuget.pkg.github.com/health-informatics-uon/index.json"

      - name: Publish to Github Packages Nuget # TODO: API Key? Or covered by authenticated source?
        run: >-
          dotnet nuget push *.nupkg
          --source github
