name: Release Hutch.Relay to Docker Hub

on:
  push:
    branches: [main]
    paths:
      - app/Hutch.Relay/**
      - test/Hutch.Relay.Tests/**
      - .github/workflows/release.Hutch.Relay.yml

env:
  namespace: hutchstack
  image-name: hutch-relay
  repo-name: ${{ github.repository }}
  registry: ghcr.io

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Docker Login
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.registry }}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Set timestamp env var
        run: echo "RUN_TIMESTAMP=$(TZ="Etc/UTC" date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.registry }}/${{ env.repo-name }}/${{ env.image-name}}
          tags: |
            ${{ github.sha }}
            ${{ env.RUN_TIMESTAMP }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: app/Hutch.Relay/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
